"""Add base_url col to members table

Revision ID: 522eafd286ef
Revises: 0a354b5c6f6c
Create Date: 2024-07-23 23:24:35.751452

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '522eafd286ef'
down_revision = '0a354b5c6f6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'base_url')
    # ### end Alembic commands ###
